# Linter config file for golangci-lint
# Example - https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  skip-dirs: []
  skip-files: []

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: false
  fast: false
  disable: []
