name: Code Coverage
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
